<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks Condition="'$(DevMode)' != 'true'">net472;netstandard2.1;net8.0;net10.0</TargetFrameworks>
        <TargetFrameworks Condition="'$(DevMode)' == 'true'">net472;net10.0</TargetFrameworks>

        <VersionPrefix>6.0.0</VersionPrefix>
        <VersionSuffix></VersionSuffix>

        <Product>FastExpressionCompiler</Product>
        <PackageId>$(Product)</PackageId>
        <Title>$(Product)</Title>
        <Description>FastExpressionCompiler 5. 10-40x times faster than Expression.Compile()</Description>
        <PackageTags>Performance;Expression;ExpressionTree;Compile;DynamicMethod;IL;ILEmit;DryIoc;ExpressionToCodeLib</PackageTags>
        <PackageReleaseNotes><![CDATA[
## v6.0.0 Major release

### Changes

- The new supported target frameworks are .NET 8.0, .NET 10.0, .NET 4.7.2, .NET Standard 2.1
- Drops .NET 6, 9 and .NET Standard 2.0 support
- #516 Change ClosureInfo into CompilerContext (should be transparent for existing code)

### Fixes

- #553 CompileFast returns wrong values when a member is accessed on an interface converted to a struct
- #536 Exception System.IndexOutOfRangeException with value objects implicit conversions starting from v5.0.3

### Performance Improvements

- #489 Try interpret a switch expression - if switch value is interpretable (constant) then select a single matched branch
- #375 Use UnsafeAccess in net8+ and UnsafeAccessType in net10+
- #135 Optimize Branches to Small Branches
- #351 Use internals of DynamicMethod

        ]]>
        </PackageReleaseNotes>
        <AssemblyName>$(Product)</AssemblyName>
        <AssemblyTitle>$(Product) $(TargetFramework)</AssemblyTitle>
        <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
        <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0"/>
    </ItemGroup>
</Project>
