<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks Condition="'$(DevMode)' != 'true'">net472;net8.0;net10.0</TargetFrameworks>
        <TargetFrameworks Condition="'$(DevMode)' == 'true'">net472;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\FastExpressionCompiler\FastExpressionCompiler.csproj" />
    </ItemGroup>
</Project>
